### ISSUE TITLE
SDK adjustments

### ISSUE THREAD

**Issue by ndzik** [perun-network/erdstall-ts-sdk#10]
- [x] Adapt `subscribe()` call to new backend implementation:
    - [x] `subscribe("balanceProof", filterArgs)`
    - [x] `subscribe("txs")`
    - [x] Also add a way to subscribe to both in a single call.
    - [x] `BalanceProof`s have to be adapted to new backend implementation, see `erdstall-operator`.
- [x] Add `subscribe()` to public `Erdstall` interface:
    - SDK would hang up if a user connects to Erdstall without subscribing, because it expects to receive `TxReceipt`s.
    - Erdstall backend would need to pack `TxReceipts` in a `Result` call.
- [x] Add convenience constructors for `LedgerConnection` and `EnclaveConnection`:
    - Some users might not want to directly participate in Erdstall by issuing transactions, but just want to listen to events happening.
- [x] Move `EnclaveConnection` interface into `erdstall.ts`
- [x] Move the `subscribe()` interface method into some interface, this might be `EnclaveWatcher` or a new `Subscriber`.
- [x] Expose common namespace in the top-level `index.ts`, to ease importing from the SDK.

**Comment by RmbRT** [comment]
- [ ] `Client.erdstallConn`: make into `Promise/Future<LedgerConnection>`

**Comment by ndzik** [comment]
All points were already addressed, are stale or already more advanced in their implementation than what this issue describes. Therefore closing it.
