### ISSUE TITLE
Custom use of `TypedJSON` on client side not working.

### ISSUE THREAD

**Issue by ndzik** [perun-network/erdstall-ts-sdk#12]
When a client, who is using our SDK, would try to go low level and implement some custom `EnclaveProvider` `TypedJSON` seems not to be initialised correctly.

Calls like `TypedJSON.parse(<my-event-json>, sdk.api.result.Result)` do not return the expected `Result` type indicating that `TypedJSON` does not call our defined en-/decoding handlers.

However, using the `Enclave` itself works fine.

**Comment by sebastianst** [comment]
This should be fixed by using the re-exported TypedJSON, right? #30
