### ISSUE TITLE
Extend end-2-end test with Token and PerunArt deployment and proper withdrawals.

### ISSUE THREAD

**Issue by sebastianst** [perun-network/erdstall-ts-sdk#131]
The end-2-end test at `src/e2e/sdk_remote_integration.spec.ts` currently tests NFT minting and trading, but only of an NFT that doesn't actually exist. It also doesn't test withdrawals. And has a few other issues.

- [x] Update the generated `operator.cfg` so that it deploys the token and nft contracts. You can also remove the unused `ResponseDuration` parameter (this can actually also be removed in the core repo's `operator.Config` struct).
  - [x] The operator should automatically register the token contract types `ERC20` and `ERC721Mintable`. However, it might be necessary to still register the actual contract. Check the other tests in the core repo for how to do this... This affects the walkthrough operator.
- [x] Extend the walkthrough operator so that the test users also are prefunded with some PRN (look at the SimSetup for how this can be done). This affects the walkthrough operator.
- [x] Also deposit PRN, not only ETH.
- [x] Change the minting tests to mint `PerunArt`s.
- [x] Change the trading tests to trade `PerunArt` NFTs for `PRN` token.
- [x] Add a test at the end where all users withdraw and assert that the users hold the freshly minted NFTs.

Looking at the core generic enclave tests will also help to fill in the gaps.

**Comment by ndzik** [comment]
Related #79 and #86

**Comment by sebastianst** [comment]
I agree that it makes sense to also improve the test structure #79 . And #86 is covered by this issue.
