### ISSUE TITLE
Update `ethers` dependencies

### ISSUE THREAD

**Issue by ndzik** [perun-network/erdstall-ts-sdk#146]
The SDK seems to be using outdated `ethers` dependencies. This makes it awkward to use in external projects because depending on whether one uses `yarn` or `npm` to resolve project dependencies one receives the error:

```
Argument of type 'JsonRpcSigner' is not assignable to parameter of type 'Signer'.
The types returned by 'provider.addListener(...).resolveName(...)' are incompatible between these types. 
Type 'Promise<string | null>' is not assignable to type 'Promise<string>'. 
Type 'string | null' is not assignable to type 'string'. Type 'null' is not assignable to type 'string'.
 ```
 
 This should be solvable by updating `ethers` together with the contract bindings, which is related to `typechain`.

**Comment by RmbRT** [comment]
On hold until `hardhat compile` supports ethers v6

**Comment by RmbRT** [comment]
Done
