### ISSUE TITLE
Pass epoch and block number in phase shift event

### ISSUE THREAD

**Issue by sebastianst** [perun-network/erdstall-ts-sdk#76]
A phase shift handler currently only receives a signal without any information. We could pass the old epoch number and block number to the handler as an
```ts
interface PhaseShiftEvent {
  epoch: number; // just passed epoch
  blockNumber: number;
}
```

**Comment by ndzik** [comment]
`blockNumber` still missing. Have to look in core to see if this is still viable.

**Comment by ndzik** [comment]
Bumping this issue up again. It is small and came up recently when grooming our backlog.

**Comment by RmbRT** [comment]
Epochs are now based on timestamps.
